### PR TITLE
Logout Functionality Added

### PR DESCRIPTION
**Pull request by DevSwayam**
So there is something i want to discuss @BisiOlaYemi @vwakesahu i added logout functionality, and removing the JWT from local storage but the cache is not getting refreshed. hence i am realoading the page after logout. It probably counted as a bad user experience. Does anyone one of you know wny better method?

### CODE REVIEW

**Comment by BisiOlaYemi** [comment]
Which of the hooks Did you use? Try UseEffect to fetch fresh API. Or consider handle Redirect to take user to fresh page

**Comment by DevSwayam** [comment]
> Which of the hooks Did you use? Try UseEffect to fetch fresh API. Or consider handle Redirect to take user to fresh page

Good question. I have used so many hooks and year I am using useEffect and providing the user info token as a dependency parameter so that it will refresh if token is being removed. It is getting refreshed to but whats not working is cache is not getting clear

**Comment by BisiOlaYemi** [comment]
Then, the problem is with cache itself. Use cache control and declare it as no store. Like the following: Cache-Control: no-store

But if you used axios then you have to consider declaring axios interceptor to clear the cache...

**Comment by DevSwayam** [comment]
> Then, the problem is with cache itself. Use cache control and declare it as no store. Like the following: Cache-Control: no-store
> 
> But if you used axios then you have to consider declaring axios interceptor to clear the cache...

Forget it we will reload the page. Its easy

**Pull request merged**
